### ISSUE TITLE
Question regarding model?

### ISSUE THREAD

**Issue by AziRizvi** [vladmandic/rife#2]
I don't really have an "issue" per-se I just had a general question if you wouldn't mind answering, the girl in the pictures that you've uploaded and her body looks quite realistic, would you mind sharing what stable diffusion model, sampling method & sampling steps and other settings that you used to create it? I would really really appreciate it.

Thanks!

**Comment by vladmandic** [comment]
model is standard `v1-5-pruned-emaonly` and vae is `vae-ft-ema-560000-ema-pruned`  
girl is a textual inversion i've trained  

i'm sorry, but seems like during last "cleanup" i've deleted that batch, so no longer have exact prompt and params used, but as far as i recall, it was quite a simple prompt (something like "beautiful young woman <ti-name> sitting on a bed, posing, high detailed, etc...") and using DPM2 Karras sampler with 25 steps
